routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/','HomeController@index')->name('root');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/products','ProductController');
Route::resource('/shoppingCart','ShoppingCartController');
Route::name('admin.')->group(function () {
  Route::group(['prefix' => 'dashboard',  'middleware' => 'auth'],function () {
    Route::get('home','Admin\AdminController@home')->name('home');
    Route::resource('categories','Admin\CategoryController');
    Route::resource('products','Admin\ProductController');
  });
});
Route::get('/clearCart', 'ShoppingCartController@clearShoppingCart')->name('clearShoppingCart');

Route::post('/checkout', 'OrderController@payWithAuthorize')->name('checkout');

Route::get('/shipping', 'OrderController@shipping')->name('shipping');

Route::post('/shippment', 'OrderController@shippmentDetails')->name('shippment');

Route::get('payPal', 'OrderController@payWithPaypal')->name('payPal');

Route::get('payments', 'OrderController@payments')->name('payments');

Route::get('paymentStore', 'OrderController@storePayment')->name('paymentStore');

Route::get('contact', 'HomeController@contact')->name('contact');

Route::post('contactMessage', 'HomeController@contactMessage')->name('contactMessage');

Route::post('guestRegistration', 'Auth\RegisterController@guestRegistration')->name('guestRegistration');

resources/views/contact.blade.php
@extends('layouts.master')

@section('content')
  @if (Session::has('status'))
   <div class="d-flex justify-content-center alert alert-success">
    <h4>{{session::get('status')}}</h4>
   </div>
   @endif
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 pt-50 pb-50">
            <div class="card">
                {{-- <div class="card-header">{{ __('Login') }}</div> --}}

                <div class="card-body">
                    <form method="POST" action="{{ route('contactMessage') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-sm-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('email') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-sm-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="message" class="col-sm-4 col-form-label text-md-right">{{ __('Message') }}</label>

                            <div class="col-md-6">
                                {{-- <input id="message" type="text" class="form-control{{ $errors->has('message') ? ' is-invalid' : '' }}" name="message" value="{{ old('message') }}" required autofocus> --}}
                                  <textarea name="message" class="form-control{{ $errors->has('message') ? ' is-invalid' : '' }}" rows="8" cols="80">
                                    {{old('message')}}
                                  </textarea>
                                @if ($errors->has('message'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('message') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-6">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>

                                {{-- <a class="btn btn-link" href="{{ route('password.request') }}">
                                    {{ __('Forgot Your Password?') }}
                                </a> --}}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/delivery.blade.php
@extends('layouts.master')
@section('content')
  @if (Session::has('status'))
   <div class="d-flex justify-content-center alert alert-success">
    <h4>{{session::get('status')}}</h4>
   </div>
   @endif
   @if ($errors->any())
    <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                   <li>{{ $error }}</li>
               @endforeach
           </ul>
    </div>
  @endif
  <div class="container">
    <form class="" action="{{route('shippment')}}" method="post">
      {{ csrf_field() }}
    <div class="col-md-12">
       @if ($userShippmenet == null)
         <div class="row">
           <div class="form-group col-md-6">
             <label for="">Full name</label>
             <input type="text" required name="fullName" value="{{old('fullName')}}" class="form-control" id="" placeholder="First Last">
           </div>
           <div class="form-group col-md-6">
             <label for="">Phone #</label>
             <input type="text" required name="phone" value="{{old('phone')}}" class="form-control" id="" placeholder="Please enter your phone">
           </div>
           <div class="form-group col-md-6">
             <label for="">City</label>
             <input type="text" required name="city" value="{{old('city')}}" class="form-control" id="" placeholder="Please enter your city">
           </div>
           <div class="form-group col-md-6">
             <label for="">Address</label>
             <input type="text" required name="address" value="{{old('address')}}" class="form-control" id="" placeholder="Please enter your address">
           </div>
         </div>

       @else
         <div class="row">
           <div class="form-group col-md-6">
             <label for="">Full name</label>
             <input type="text" required name="fullName" value="{{$userShippmenet->fullName}}" class="form-control" id="" placeholder="First Last">
           </div>
           <div class="form-group col-md-6">
             <label for="">Phone #</label>
             <input type="text" required name="phone" value="{{$userShippmenet->phone}}" class="form-control" id="" placeholder="Please enter your phone">
           </div>
           <div class="form-group col-md-6">
             <label for="">City</label>
             <input type="text" required name="city" value="{{$userShippmenet->city}}" class="form-control" id="" placeholder="Please enter your city">
           </div>
           <div class="form-group col-md-6">
             <label for="">Address</label>
             <input type="text" required name="address" value="{{$userShippmenet->address}}" class="form-control" id="" placeholder="Please enter your address">
           </div>
         </div>
       @endif
      {{-- <div class='card col-md-6'>
        <div>
          Pay securely Using your credit card.
        </div>
        <div class="card-body">
          <div class="row">
            <div class="form-group col-md-12">
              <label for="">Card Number *</label>
              <input type="text" required name="cardNumber" value="{{old('address')}}" class="form-control" id="" placeholder="**** **** **** ****">
            </div>
            <div class="form-group col-md-6">
              <label for="">Expiry (MM/YY) *</label>
              <input type="text" required name="expiry" value="{{old('address')}}" class="form-control" id="" placeholder="**** **** **** ****">
            </div>
            <div class="form-group col-md-6">
              <label for="">Card Code *</label>
              <input type="text" required name="cardCode" value="{{old('address')}}" class="form-control" id="" placeholder="**** **** **** ****">
            </div>
          </div>
        </div>
      </div> --}}
      <div class="text-center">
        <button type="submit" class="btn btn-secondary btn-block">Proceed</button>
      </div>
    </div>

  </form>

  </div>
<script type = "text/javascript">
function validation() {
  if (confirm("Are you sure want to delete?")) {
         return true;
  }
         return false;
}
});
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
  @php
     $tempIterator = 0;
  @endphp
  <div class="container">
    <div id="productsSlider" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
      @foreach ($products as $product)
       @if ($tempIterator == 0)
         <div class="carousel-item text-center active">
       @else
         <div class="carousel-item text-center" >
       @endif
        <img style="height:320px;widht:320px;" src="{{ asset('uploads/'.$product->image) }}" alt="First slide">
        <div class="carousel-caption d-none d-md-block" style="background-color: white; opacity:0.7;">
          <h5 style="color:#000;">{{$product->name}}</h5>
          <p style="color:#000;">{{str_limit($product->description)}}</p>
        </div>
      </div>
      @php
         $tempIterator++;
       @endphp
      @endforeach
      </div>
      <a class="carousel-control-prev" href="#productsSlider" role="button" data-slide="prev">
        <span class="left fa fa-chevron-left btn btn-success" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#productsSlider" role="button" data-slide="next">
        <span class="right fa fa-chevron-right btn btn-success" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      </div>
    </div>
  </div>
  @php
  // $data =  $products->splice(0,2);
  // dd($products);
  // $iteratorSlide = 0;
  $iteratoreActive = 0 ;
  @endphp
  <div class="container">
    <div class="row mt-5">

    <div class="col-md-9">
                <h3>
            Trending Products
                </h3>
    </div>
   {{-- @php
     dd($trending->count() == 4);
   @endphp --}}
    <div class="col-md-3">
                    <!-- Controls -->
                    @if ($trending->count() >= 4)
                    <div class="controls float-right">
                        <a class="left fa fa-chevron-left btn btn-success" href="#trendingSlider" data-slide="prev"></a>
                        <a class="right fa fa-chevron-right btn btn-success" href="#trendingSlider" data-slide="next"></a>
                    </div>
                    @endif
    </div>
    </div>
     <div id="trendingSlider" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        @foreach ($trending as $product)
             @if ($iteratoreActive == 0)
               <div class="carousel-item active">
             @else
               <div class="carousel-item">
             @endif
             @php
             $iteratoreActive++;
             $tempItems = $trending->splice(0,3);
             // dd();
             @endphp
              <div class="row">
            @foreach ($tempItems as $tempItem)
              <div class="card col-md-4 p-0 rounded-0 border-light">
                <img class="card-img-top" style="height:320px;widht:320px;" src="{{ asset('uploads/'.$tempItem->image) }}" alt="arwi">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item ">
                    <h3>{{$tempItem->name}}</h3>
                  </li>
                  <li class="list-group-item">$: {{$tempItem->price}}</li>
                  <li class="list-group-item p-0">
                    <form class="d-inline" action="{{ route('shoppingCart.store') }}" method="post">
                        @csrf
                        <input type="hidden" name="id" value="{{$tempItem->id}}">
                        <button type="submit" class="btn btn-secondary btn-block" name="submit">Add To Cart</button>
                    </form>
                  </li>
                </ul>
              </div>
            @endforeach
          </div>
        </div>
            @php
              if ($trending->count() == 0) {
                break;
              }
            @endphp
        @endforeach
      </div>
      {{-- <a class="carousel-control-prev" href="#trendingSlider" role="button" data-slide="prev">
        <span class="left fa fa-chevron-left btn btn-success" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#trendingSlider" role="button" data-slide="next">
        <span class="right fa fa-chevron-right btn btn-success" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a> --}}
      </div>
    </div>

@endsection

resources/views/payOrder.blade.php
@extends('layouts.master')
@section('content')
  @if (Session::has('status'))
   <div class="d-flex justify-content-center alert alert-success">
    <h4>{{session::get('status')}}</h4>
   </div>
   @endif
   @if ($errors->any())
    <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                   <li>{{ $error }}</li>
               @endforeach
           </ul>
    </div>
  @endif
  <div class="container">
    <div class="col-md-6 mb-4">

    <a href="{{route('payPal')}}" class="btn btn-primary ">Pay with PayPal</a>
   </div>
    <form  action="{{route('checkout')}}" method="post">
      {{ csrf_field() }}
    <div class="col-md-12">
        <div class="row mb-4">
        <div class='col-md-5'>
          <h6>
            <input type="radio" class="form-group" name="selector" checked>
            Pay securely Using your credit card.
          </h6>
            <div class="row">
              <div class="form-group col-md-12">
                <label for="">Card Number *</label>
                <input type="text" required name="cardNumber" @if ($user->cardNumber != null) value="{{$user->cardNumber}}" @else value="{{old('cardNumber')}}" @endif  class="form-control" id="" placeholder="**** **** **** ****">
              </div>
              <div class="form-group col-md-6">
                <label for="">Expiry (Y-M) *</label>
                <input type="text" required name="expiry" @if ($user->expiry != null) value="{{$user->expiry}}" @else value="{{old('expiry')}}" @endif class="form-control" id="" placeholder="2000-01">
              </div>
              <div class="form-group col-md-6">
                <label for="">Card Code *</label>
                <input type="text" required name="cvv"  @if ($user->cvv != null) value="{{$user->cvv}}" @else value="{{old('cvv')}}" @endif class="form-control" id="" placeholder="CVV">
              </div>
            </div>
        </div>
        <div class='col-md-5'>
          <div class="container">
            <h3>Order Summary</h3>
                <span style="font-size: 12px; line-height: 19px;">Subtotal ({{$totalItems}} items and shipping fee included)</span>   <span style="float:right">${{$price}}</span>
                <div class="mt-2">
                  Total Amount <label style="float:right; font-size:18px;">${{$price}}</label>

                </div>
          </div>
        </div>
        </div>
      {{-- <br> --}}
      <div class="text-center">
        <button type="submit" class="btn btn-secondary btn-block">Proceed</button>
      </div>
    </div>

  </form>

  </div>
@endsection

resources/views/products.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">
    <div class="card-deck mb-3 text-center">

      @foreach ($products as $product)
        @php
          // dd($product);
        @endphp
        <div class="card col-md-4 p-0 rounded-0 border-light">
          <img class="card-img-top" style="height:320px;widht:320px;" src="{{ asset('uploads/'.$product->image) }}" alt="arwi">
          <ul class="list-group list-group-flush">
            <li class="list-group-item pl-0 pr-0 border-top-0">
              <h4>{{$product->name}}</h4>
            </li>
            <li class="list-group-item">$: {{$product->price}}</li>
            <li class="list-group-item p-0">
              <form class="d-inline" action="{{ route('shoppingCart.store') }}" method="post">
                  @csrf
                  <input type="hidden" name="id" value="{{$product->id}}">
                  <button type="submit" class="btn btn-secondary btn-block" name="submit">Add To Cart</button>
              </form>
            </li>
          </ul>
        </div>
      @endforeach




    </div>

  </div>

@endsection

resources/views/shopping-cart.blade.php
@extends('layouts.master')
@section('content')
  {{-- @php
    dd($items);
  @endphp --}}
  @if (Session::has('status'))
   <div class="d-flex justify-content-center alert alert-success">
    <h4>{{session::get('status')}}</h4>
   </div>
   @endif
   @if ($errors->any())
    <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                   <li>{{ $error }}</li>
               @endforeach
           </ul>
    </div>
  @endif
  <div class="container">
    @isset($items)

    @if ($items->count() != 0)

    <div class="card-deck mb-3 shadow-sm">
      <div class="col-md-12 p-3">
         @if($items->count() == 1)
        <h3 class="float-left">You have {{$items->count()}} item in your cart</h3>
        @elseif($items->count() == 0)
          <h3 class="float-left">Cart is empty</h3>
        @elseif($items->count() > 1)
        <h3 class="float-left">You have {{$items->count()}} items in your cart</h3>
        @endif
        {{--Remove comment to show modal--}}
        <a  href = "{{ route('clearShoppingCart') }}" {{-- data-toggle="modal" data-target="#myModal" --}} class="p-2 text-dark float-right" >Clear Shopping Cart</a>
      </div>
      <div class="col-md-12 border-top d-flex p-2">
        <div class="col-md-1">
          {{-- img --}}
        </div>
        <div class="col-md-3">
          <h5>Product</h5>
        </div>
        <div class="col-md-3">
          <h5>Quantity</h5>
        </div>
        <div class="col-md-2">
          {{-- Edit Cart --}}
        </div>
        <div class="col-md-4">
          <h5>Price</h5>
        </div>
      </div>
      @foreach($items as $item)
       <div class="col-md-12 border-top d-flex p-2">
        <div class="col-md-1">
          <img src = "{{URL::asset('uploads/'.$item->image)}}" class="rounded-circle img-thumbnail" alt="">
        </div>
        <div class="col-md-3 pt-2">
          <form action="{{ route('shoppingCart.destroy',$item->itemId) }}" style="display:inline" onsubmit = "return validation()" method="post">
                {{ csrf_field() }}
               <input type='hidden' name='_method' value="delete" />
               <button type="submit" class="btn btn-sm btn-icon btn-pure btn-default" data-toggle="tooltip"
                 title="Delete Item">
                 <i class="fas fa-times" aria-hidden="true"></i>
               </button>
          </form>
         {{$item->name}}
        </div>
        <div class="col-md-3 pt-2 pl-4">
          <form action="{{ route('shoppingCart.update',$item->itemId) }}" style="display:inline" method="post">
                {{ csrf_field() }}
                <input type='hidden' name='_method' value="PUT" />
                <input type="number" class="form-control col-md-12" name="quantity" value = "{{ $item->itemQuantity }}" min="1" >
        </div>
        <div class="col-md-2 pt-2 pl-4">
          <button type="submit" class="btn btn-sm btn-icon btn-pure btn-default" data-toggle="tooltip"
            title="Edit Item">
            <i class="fas fa-edit" aria-hidden="true"></i>
          </button>
        </div>
       </form>
        <div class="col-md-4 pt-2">
          {{$item->price}} x {{$item->itemQuantity}} = {{$item->price * $item->itemQuantity}}
        </div>
      </div>
    @endforeach
  </div>
  <div class="float-right">
  <a href=" {{ route('shipping') }}" class="btn btn-secondary btn-block">Proceed to Checkout</a>
  </div>

    @else
       <div class="col-md-12 text-center p-5 ">
            <h3>Cart is empty</h3>
       </div>
       <div class="float-right">
       <a href=" {{ route('products.index') }}" class="btn btn-secondary btn-block">Continue Shopping</a>
       </div>
    @endif
  @endisset
  @if (!isset($items))
    <div class="col-md-12 text-center p-5 ">
         <h3>Cart is empty</h3>
    </div>
    <div class="float-right">
    <a href=" {{ route('products.index') }}" class="btn btn-secondary btn-block">Continue Shopping</a>
    </div>
  @endif

</div>
<script type = "text/javascript">
function validation() {
  if (confirm("Are you sure want to delete?")) {
         return true;
  }
         return false;
}
});
</script>
@endsection