routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/','HomeController@index')->name('root');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/products','ProductController');
Route::resource('/shoppingCart','ShoppingCartController');
Route::name('admin.')->group(function () {
  Route::group(['prefix' => 'dashboard',  'middleware' => 'auth'],function () {
    Route::get('home','Admin\AdminController@home')->name('home');
    Route::resource('categories','Admin\CategoryController');
    Route::resource('products','Admin\ProductController');
  });
});
Route::get('/clearCart', 'ShoppingCartController@clearShoppingCart')->name('clearShoppingCart');

Route::post('/checkout', 'OrderController@payWithAuthorize')->name('checkout');

Route::get('/shipping', 'OrderController@shipping')->name('shipping');

Route::post('/shippment', 'OrderController@shippmentDetails')->name('shippment');

Route::get('payPal', 'OrderController@payWithPaypal')->name('payPal');

Route::get('payments', 'OrderController@payments')->name('payments');

Route::get('paymentStore', 'OrderController@storePayment')->name('paymentStore');

Route::get('contact', 'HomeController@contact')->name('contact');

Route::post('contactMessage', 'HomeController@contactMessage')->name('contactMessage');

Route::post('guestRegistration', 'Auth\RegisterController@guestRegistration')->name('guestRegistration');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Product;
use App\CartItem;
use App\OrderItem;
use Session;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

          $categories = Category::all();
          return view('dashboard.categories.index' , compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

         $request->validate([
            'name' => 'required|string|max:255|unique:categories'
          ]);

        /*
          $this->validate(
                            $request,
                            [
                              'name' => 'required|string|max:255'
                            ],
                            [
                                  'name.unique:categories' => 'Category already exists',
                            ]
                      );
                         */

         $category = new Category;
         $category->name = $request->name;
         $category->save();
         Session::flash("status" , "Category Added Successfully");
         return redirect(route('admin.categories.index'));
     }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($categoryId)
    {
        $categories = Category::all();
        $categoryForEdit = Category::find($categoryId);
        return view("dashboard.categories.index" , compact("categories" , "categoryForEdit"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $categoryId)
    {

      $request->validate([
         'name' => 'required|string|max:255|unique:categories'
       ]);

      $category = Category::find($categoryId);
      $category->name = $request->name;
      $category->save();
      Session::flash("status" , "Category Updated Successfully");
      return redirect(route('admin.categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($categoryId)
    {

      $products = Product::where('categoryId' , '=' , $categoryId)->get();
      if(count($products) > 0)
      {
         foreach($products as $product)
         {

        $cartItems = CartItem::where('productId', '=', $product->id)->get();

        if (count($cartItems) > 0) {

                foreach ($cartItems as $cartItem) {
                      $cartItem->delete();
                }

            }
            $orderItems = OrderItem::where('productId', '=', $product->id)->get();

            if (count($orderItems) > 0) {

                    foreach ($orderItems as $orderItem) {
                          $orderItem->delete();
                    }
            }
          $productForDelete = Product::find($product->id);
          if(!is_null($productForDelete))
          {

              $productForDelete->delete();
          }

        }

     }

     $categoryForDelete = Category::find($categoryId);
     if(!is_null($categoryForDelete))
     {

         $categoryForDelete->delete();
     }
     
        Session::flash('status', 'Category Deleted Successfully');
        return redirect(route('admin.categories.index'));
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/dashboard/categories/index.blade.php
@extends('layouts.dashboard')
@section('body')
  <script type="text/javascript">
  </script>
  <style>
 .category-padding{
    padding-right : 160px !important;
  }
  </style>
  @if (Session::has('status'))
  <div class="d-flex justify-content-center alert alert-success">
   <h4>{{session::get('status')}}</h4>
  </div>
  @endif
  @if ($errors->any())
   <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
   </div>
 @endif
<div class="row">
  <div class="col-md-8">
    <!-- Panel Static Labels -->
    <div class="panel panel-primary panel-line" style="margin:10px;">
      <h3 class="panel-title panel-heading">Categories</h3>
      <div class="panel-body container-fluid">
        <div class="table-responsive">
            <table class="table table-hover dataTable table-striped w-full" id="categories">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Action</th>
               </tr>
              </thead>
              <tbody>
               @foreach ($categories as $category)
                <tr>
                  <td class = "text-overflow">{{str_limit($category->name,100)}}</td>
                  <td>
                    <a  title="Edit Category" class = "fas fa-edit" href="{{route('admin.categories.edit',$category->id)}}">
                    </a>
                    <form action="{{route('admin.categories.destroy',$category->id)}}" style="display:inline" onsubmit="return validation()" method="post">
                          {{ csrf_field() }}
                         <input type='hidden' name='_method' value="delete" />
                         <button type="submit" data-toggle="tooltip" class="btn btn-sm btn-danger btn-icon btn-pure btn-default" data-original-title="Delete Product">
                           <i class="fas fa-times" aria-hidden="true"></i>
                         </button>
                    </form>
                  </td>
               </tr>

                @endforeach
              </tbody>
            </table>
          </div>
        {{-- </div> --}}
      </div>
    </div>
    <!-- End Panel Static Labels -->
  </div>
  <div class="col-md-4">
    <!-- Panel Floating Labels -->
    <div class="panel  panel-primary panel-line" style="margin:10px;">
      <div class="panel-heading">
        @if (isset($categoryForEdit))
          <h3 class="panel-title">Edit Category</h3>
        @else
          <h3 class="panel-title">Add Category</h3>
        @endif
      </div>
      <div class="panel-body col-md-12 ">
                    <div class="col-md-12"  id="formDiv">
                    @if (isset($categoryForEdit))
                      {!! Form::open(array('route' => ['admin.categories.update','id'=>$categoryForEdit->id], 'method' => 'PUT','style'=>'width:100%;','id'=>'formmain', 'enctype' => 'multipart/form-data')) !!}
                      <input type='hidden' name='_method' value="PUT" />
                    @else
                      {!! Form::open(array('route' => 'admin.categories.store', 'method' => 'POST', 'style'=>'width:100%')) !!}
                    @endif
                         {{ csrf_field() }}

                    <div class="QDiv0 mt-20" style="margin-left: -15px;">
                    <div class=" col-md-50 mt 10" >
                      <div class="form-group form-material">
                        @if (isset($categoryForEdit))
                          <input type="text" style="margin-top: -25px;"  class="form-control"  name="name" value="{{$categoryForEdit->name}}" placeholder="Enter Category Name" />
                          <span style="color:red; float:right; margin-top:-25px;">*</span>
                        @else
                          <input type="text" style="margin-top: -25px;"  class="form-control" name="name" value="" placeholder="Enter Category Name" />
                          <span style="color:red; float:right; margin-top:-25px;">*</span>
                        @endif
                       </div>
                    </div>
                  </div>
                    <div class="col-md-40 " name="second-element">
                        {!! Form::button('Submit',['type'=>'submit','style'=>'background:#6c406e; float:right; color: white; hover: red;', 'class'=>' btn btn-secondary', 'id'=>'submit']) !!}
                    </div>
                    {!! Form::close() !!}
                  </div>
        </div>
    </div>
  </div>
</div>
@endsection
@section('js')
<script type="text/javascript">
$(document).ready(function() {

   $('#categories').DataTable();
});
 function validation() {
      if (confirm("Are you sure want to delete?")) {
             return true;
      }
             return false;
  }
</script>
@endsection