routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/','HomeController@index')->name('root');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/products','ProductController');
Route::resource('/shoppingCart','ShoppingCartController');
Route::name('admin.')->group(function () {
  Route::group(['prefix' => 'dashboard',  'middleware' => 'auth'],function () {
    Route::get('home','Admin\AdminController@home')->name('home');
    Route::resource('categories','Admin\CategoryController');
    Route::resource('products','Admin\ProductController');
  });
});
Route::get('/clearCart', 'ShoppingCartController@clearShoppingCart')->name('clearShoppingCart');

Route::post('/checkout', 'OrderController@payWithAuthorize')->name('checkout');

Route::get('/shipping', 'OrderController@shipping')->name('shipping');

Route::post('/shippment', 'OrderController@shippmentDetails')->name('shippment');

Route::get('payPal', 'OrderController@payWithPaypal')->name('payPal');

Route::get('payments', 'OrderController@payments')->name('payments');

Route::get('paymentStore', 'OrderController@storePayment')->name('paymentStore');

Route::get('contact', 'HomeController@contact')->name('contact');

Route::post('contactMessage', 'HomeController@contactMessage')->name('contactMessage');

Route::post('guestRegistration', 'Auth\RegisterController@guestRegistration')->name('guestRegistration');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="">
  <title>oShop Dashboard</title>
  <link rel="apple-touch-icon" href="{{asset('dashboard/assets/images/apple-touch-icon.png')}}">
  <link rel="shortcut icon" href="{{asset('dashboard/assets/images/favicon.ico')}}">
  <!-- Stylesheets -->
  <link rel="stylesheet" href="{{asset('dashboard/global/css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/css/bootstrap-extend.min.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/assets/css/site.min.css')}}">
  <!-- Plugins -->
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/animsition/animsition.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/asscrollable/asScrollable.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/switchery/switchery.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/intro-js/introjs.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/slidepanel/slidePanel.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/flag-icon-css/flag-icon.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/waves/waves.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/datatables.net-bs4/dataTables.bootstrap4.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/datatables.net-responsive-bs4/dataTables.responsive.bootstrap4.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/datatables.net-buttons-bs4/dataTables.buttons.bootstrap4.css')}}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
  <!-- Fonts -->
  <link rel="stylesheet" href="{{asset('dashboard/global/fonts/material-design/material-design.min.css')}}">
  <link rel="stylesheet" href="{{asset('dashboard/global/fonts/brand-icons/brand-icons.min.css')}}">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link rel="stylesheet" href="{{asset('dashboard/global/vendor/dropify/dropify.css')}}">
  <!--[if lt IE 9]>
    <script src="{{asset('dashboard/global/vendor/html5shiv/html5shiv.min.js')}}"></script>
    <![endif]-->
  <!--[if lt IE 10]>
    <script src="{{asset('dashboard/global/vendor/media-match/media.match.min.js')}}"></script>
    <script src="{{asset('dashboard/global/vendor/respond/respond.min.js')}}"></script>
    <![endif]-->
  <!-- Scripts -->
  <script src="{{asset('dashboard/global/vendor/breakpoints/breakpoints.js')}}"></script>
  <script>
  Breakpoints();
  </script>
</head>
<body class="animsition">
  <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
  <nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"
      data-toggle="menubar">
        <span class="sr-only">Toggle navigation</span>
        <span class="hamburger-bar"></span>
      </button>
      <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse"
      data-toggle="collapse">
        <i class="icon md-more" aria-hidden="true"></i>
      </button>
      <div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
        <img class="navbar-brand-logo" src="{{asset('dashboard/assets/images/logo.png')}}" title="Remark">
        <span class="navbar-brand-text hidden-xs-down"> Remark</span>
      </div>
      <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-search"
      data-toggle="collapse">
        <span class="sr-only">Toggle Search</span>
        <i class="icon md-search" aria-hidden="true"></i>
      </button>
    </div>
    <div class="navbar-container container-fluid">
      <!-- Navbar Collapse -->
      <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
        <!-- Navbar Toolbar -->
        <ul class="nav navbar-toolbar">
          <li class="nav-item hidden-float" id="toggleMenubar">
            <a class="nav-link" data-toggle="menubar" href="#" role="button">
              <i class="icon hamburger hamburger-arrow-left">
                  <span class="sr-only">Toggle menubar</span>
                  <span class="hamburger-bar"></span>
                </i>
            </a>
          </li>
      </ul>
        <!-- End Navbar Toolbar -->
        <!-- Navbar Toolbar Right -->
        <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false"
            data-animation="scale-up" role="button">
              <span class="avatar avatar-online">
                <img src="{{asset('dashboard/global/portraits/5.jpg')}}" alt="...">
                <i></i>
              </span>
            </a>
            <div class="dropdown-menu" role="menu">
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon md-account" aria-hidden="true"></i> Profile</a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon md-card" aria-hidden="true"></i> Billing</a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon md-settings" aria-hidden="true"></i> Settings</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon md-power" aria-hidden="true"></i> Logout</a>
            </div>
          </li>
      </ul>
        <!-- End Navbar Toolbar Right -->
      </div>
      <!-- End Navbar Collapse -->
      <!-- Site Navbar Seach -->
      <div class="collapse navbar-search-overlap" id="site-navbar-search">
        <form role="search">
          <div class="form-group">
            <div class="input-search">
              <i class="input-search-icon md-search" aria-hidden="true"></i>
              <input type="text" class="form-control" name="site-search" placeholder="Searchdashboard.">
              <button type="button" class="input-search-close icon md-close" data-target="#site-navbar-search"
              data-toggle="collapse" aria-label="Close"></button>
            </div>
          </div>
        </form>
      </div>
      <!-- End Site Navbar Seach -->
    </div>
  </nav>
  <div class="site-menubar">
    <div class="site-menubar-body">
      <div>
        <div>
          <ul class="site-menu" data-plugin="menu">
            <li class="site-menu-category">General</li>
            <li class="site-menu-item">
              <a class="animsition-link" href="{{ route('admin.categories.index') }}">
                <i class="site-menu-icon fas fa-tags" aria-hidden="true"></i>
                <span class="site-menu-title">Categories</span>
              </a>
            </li>

            <li class="site-menu-item">
              <a class="animsition-link" href="{{ route('admin.products.index') }}">
                <i class="site-menu-icon fab fa-product-hunt" aria-hidden="true"></i>
                <span class="site-menu-title">Products</span>
              </a>
            </li>
           </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- Page -->
  <div class="page">
    @yield('body')
  </div>
  <!-- End Page -->
    <!-- Core  -->
  <script src="{{asset('dashboard/global/vendor/babel-external-helpers/babel-external-helpers.js')}}"></script>

  <script src="{{asset('dashboard/global/vendor/jquery/jquery.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/tether/tether.js')}}"></script>

  <script src="{{ asset('js/select2.min.js') }}" ></script>

  <script src="{{asset('dashboard/global/vendor/bootstrap/bootstrap.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/animsition/animsition.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/mousewheel/jquery.mousewheel.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/asscrollbar/jquery-asScrollbar.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/asscrollable/jquery-asScrollable.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/ashoverscroll/jquery-asHoverScroll.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/waves/waves.js')}}"></script>
  <!-- Plugins -->
  <script src="{{asset('dashboard/global/vendor/switchery/switchery.min.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/intro-js/intro.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/screenfull/screenfull.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/slidepanel/jquery-slidePanel.js')}}"></script>
  <!-- Scripts -->
  <script src="{{asset('dashboard/global/js/State.js')}}"></script>
  <script src="{{asset('dashboard/global/js/Component.js')}}"></script>
  <script src="{{asset('dashboard/global/js/Plugin.js')}}"></script>
  <script src="{{asset('dashboard/global/js/Base.js')}}"></script>
  <script src="{{asset('dashboard/global/js/Config.js')}}"></script>
  <script src="{{asset('dashboard/assets/js/Section/Menubar.js')}}"></script>
  <script src="{{asset('dashboard/assets/js/Section/GridMenu.js')}}"></script>
  <script src="{{asset('dashboard/assets/js/Section/Sidebar.js')}}"></script>
  <script src="{{asset('dashboard/assets/js/Section/PageAside.js')}}"></script>
  <script src="{{asset('dashboard/assets/js/Plugin/menu.js')}}"></script>
  <script src="{{asset('dashboard/global/js/config/colors.js')}}"></script>
  {{-- <script src="{{asset('dashboard/assets/js/config/tour.js')}}"></script> --}}
  <script src="{{ asset('dashboard/global/vendor/datatables.net/jquery.dataTables.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-fixedheader/dataTables.fixedHeader.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-fixedcolumns/dataTables.fixedColumns.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-rowgroup/dataTables.rowGroup.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-scroller/dataTables.scroller.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-select-bs4/dataTables.select.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-responsive/dataTables.responsive.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-responsive-bs4/responsive.bootstrap4.js') }}"></script>
  <script src="{{ asset('dashboard/global/vendor/datatables.net-buttons/dataTables.buttons.js') }}"></script>

  <script>
  Config.set('assets', '{{asset('assets')}}');
  </script>
  <!-- Page -->
  <script src="{{asset('dashboard/assets/js/Site.js')}}"></script>
  <script src="{{asset('dashboard/global/js/Plugin/asscrollable.js')}}"></script>
  <script src="{{asset('dashboard/global/js/Plugin/slidepanel.js')}}"></script>
  <script src="{{asset('dashboard/global/js/Plugin/switchery.js')}}"></script>
  <script src="{{asset('dashboard/global/vendor/dropify/dropify.min.js')}}"></script>

  @yield('js')

  <script>
  (function(document, window, $) {
    'use strict';
    var Site = window.Site;
    $(document).ready(function() {
      Site.run();
    });
  })(document, window, jQuery);
  </script>
</body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ asset('favicon.png') }}">

    <title>oShop</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('main.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="{{ route('root') }}">
                  <img src="{{ asset('favicon.png') }}" class="img-fluid logo" alt="oShop">
        </a>
      </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{{ route('products.index') }}">Products</a>
        <a class="p-2 text-dark" href="{{ route('shoppingCart.index') }}">Shoping Cart</a>
        <a class="p-2 text-dark" href="{{ route('contact') }}">Contact</a>
        {{-- <a class="p-2 text-dark" href="#">About</a> --}}
      </nav>
      @auth ()
        <a  class="p-2 text-dark" href="{{ route('logout') }}"
                     onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();" >Logout</a>
       <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
           @csrf
       </form>
      @else
        <div>

          <a class="btn btn-outline-primary" href="{{ route('login') }}">Sign in</a>
          <a class="btn btn-outline-primary" href="{{ route('register') }}">Register</a>
        </div>
      @endauth
    </div>
    @yield('content')
    <div class="container">
      <footer class="pt-4 my-md-5 pt-md-5">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="../../assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
              <li><a class="text-muted" href="#">Stuff for developers</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
              <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>

    </div>
   <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{{ asset('popper.min.js') }}"></script>
    <script src="{{ asset('bootstrap.min.js') }}"></script>
    <script>

    function isValidEmailAddress(email)
    {
      var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      return re.test(String(email).toLowerCase());
    }
    function validateEmail()
    {
        var email = $('#guestEmail').val();

        if (email.length < 3 || !isValidEmailAddress(email)) {
         alert('Please enter a valid email');
         return 0;
         }
     $('#guestForm').submit();
    }
    @if ($errors->has('email'))
      @if ($errors->first('email') == 'The email has already been taken.')
      $(document).ready(function(){
        $('#exampleModalCenter').modal('show');
      });
      @endif
    @endif
    </script>

  </body>
</html>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
       {{-- <div class="modal-header invitation-header-pop-up">
        <h5 class="modal-title invitation-title" id="exampleModalLabel">Registration Questions</h5>
      </div> --}}
      <div class="modal-body modal-body-invitation">
        {{--
        @php
          $increment = 0;
        @endphp
           @foreach ($event->questions as $question)
                       @php
                         $increment++;
                       @endphp
                       @if($increment == 1)

                       <label style = "display: block;" class="form-control-label"><b>{{$question->question}}</b></label>
                      @else
                         <label style = "display: block; margin-top : 7px;" class="form-control-label"><b>{{$question->question}}</b></label>
                       @endif
                       @foreach($question->answers as $questionAnswer)
                       <input type="text" style = "display: block; width : 300px;" value = "{{$questionAnswer->answer}}" disabled>
                       @endforeach
            @endforeach
      </div>
             {{--@foreach($question->answers as $answer)
             @endforeach --}}
             {{-----<br> --}}
             <div class="appended-modal-body-invitation" id="modelBody">
               Do you want to clear the cart?
             </div>
      <div class="modal-footer invitation-footer-pop-up">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>